name: Daily Commit Workflow

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  commit_job:
    runs-on: ubuntu-latest
    name: Commit Job 21f1004710@ds.study.iitm.ac.in

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          mkdir -p workflow_data
          echo "Last run: $(date +'%Y-%m-%d %H:%M:%S')" >> workflow_data/last_run.txt

      - name: Commit Changes (allow empty)
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "21f1004710@ds.study.iitm.ac.in"
          git add workflow_data/last_run.txt
          git commit -m "Daily commit from workflow $(date)" --allow-empty

      - name: Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD
