name: Daily Commit Workflow

on:
  schedule:
    - cron: "30 8 * * *"
  workflow_dispatch:

jobs:
  commit_job:
    runs-on: ubuntu-latest
    name: Commit Job 21f1004710@ds.study.iitm.ac.in

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step name includes the email
      - name: Updating timestamp for 21f1004710@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit Changes
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "21f1004710@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Daily commit from workflow $(date)" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
