name: Daily Commit Workflow

# Run once per day at a specific time (e.g., 08:30 UTC)
on:
  schedule:
    - cron: "30 8 * * *"

jobs:
  commit_job:
    runs-on: ubuntu-latest
    name: Commit Job for 21f1004710@ds.study.iitm.ac.in

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Make a small change (update a timestamp file)
      - name: Update timestamp
        run: |
          echo "Last run: $(date)" > last_run.txt

      # Commit the change
      - name: Commit Changes
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "21f1004710@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Daily commit from workflow $(date)" || echo "No changes to commit"

      # Push commit back to the repo
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
